version: '3'
services:
  nginx:
    depends_on:
      - jwp-trello
    image: jwp/nginx
    links:
      - jwp-trello:jwp_trello
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - mafia:/etc/letsencrypt
      - mafia-data:/data/letsencrypt
  jwp-trello:
    image: wkddngus5/jwp-trello
    links:
      - db
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: roalclsrn
      MYSQL_USER: dev
      MYSQL_PASSWORD: roalclsrn
      MYSQL_DATABASE: jwp-trello
    volumes:
      - trello-datavolume:/var/lib/mysql
volumes:
  trello-datavolume:
  mafia:
  mafia-data:
